name: Build VeinMiner for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build VeinMiner project
      run: dotnet build TShockVeinMiner.csproj --configuration Release --runtime linux-arm64

    - name: Publish VeinMiner for ARM64
      run: dotnet publish TShockVeinMiner.csproj --configuration Release --runtime linux-arm64 --output publish

    - name: Upload VeinMiner.dll
      uses: actions/upload-artifact@v4
      with:
        name: VeinMiner
        path: publish/VeinMiner.dll
