name: Build VeinMiner for ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --runtime linux-arm64

      - name: Upload VeinMiner.dll
        uses: actions/upload-artifact@v4
        with:
          name: VeinMiner
          path: |
            bin/Release/net6.0/linux-arm64/publish/VeinMiner.dll


